name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - jupyterlab
  - nbconvert
  - pandoc
  - pandas
  - numba
  - numpy
  - matplotlib
  - networkx
  - sphinx=2.4.4
  - interpolation
  - seaborn
  - pip:
    - sphinxcontrib-jupyter==0.5.7
    - sphinxcontrib-bibtex
    - quantecon
    - joblib
